### ISSUE TITLE
css文件夹下面少了文件

### ISSUE THREAD

**Issue by ghost** [1506085843/XTool#1]
![屏幕截图 2023-05-22 093912](https://github.com/1506085843/XTool/assets/58473770/c9cded16-2924-4399-96c0-16f5d150b490)
麻烦补充一下

**Comment by 2017517110** [comment]
把jfoenix-8.0.1.jar下面的css文件拷贝到项目中css文件下就好了
![屏幕截图 2023-05-22 110025](https://github.com/1506085843/XTool/assets/58473770/09d33425-b85a-4ff8-ab38-a9d1ff2c7f2a)

**Comment by ghost** [comment]
> ![屏幕截图 2023-05-22 093912](https://user-images.githubusercontent.com/58473770/239781947-c9cded16-2924-4399-96c0-16f5d150b490.png) 麻烦补充一下

把jfoenix-8.0.10.jar下面的css文件拷贝到项目中css文件夹去就好了
![image](https://github.com/1506085843/XTool/assets/58473770/1970c34e-feab-4f04-b938-0907708a76e3)

**Comment by 1506085843** [comment]
感谢你提出的问题，现已把缺失的文件加入到了css文件夹下
