### ISSUE TITLE
中文乱码问题

### ISSUE THREAD

**Issue by LzyAllmen** [1506085843/XTool#2]
你本地没有中文错误的问题么 ![image](https://github.com/1506085843/XTool/assets/26646651/9dd4287e-48b9-4482-9262-c32141393da6)

**Comment by 1506085843** [comment]
编码问题，我本地是没问题的。你可以使用notepad++ 打开 resources/fxml/ui/ 下面的fxml类型的那些文件看下中文有没有乱码并且检查下是不是UTF-8的编码格式，不是的话改为 UTF-8 格式，保存后再运行代码就可以了
